# Generated by Django 4.2.6 on 2023-10-20 10:41

from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "FEMALE"), ("Male", "MALE")], max_length=6
                    ),
                ),
                ("age", models.IntegerField()),
                ("breed", models.CharField(default="mongrel", max_length=63)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("Big", "BIG"),
                            ("Middle", "MIDDLE"),
                            ("Small", "SMALL"),
                        ],
                        max_length=6,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=63, null=True)),
                ("story", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to=pets.models.pet_image_file_path
                    ),
                ),
                (
                    "animal_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pets.pettype"
                    ),
                ),
            ],
        ),
    ]
