# Generated by Django 4.2.6 on 2023-10-19 10:45

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="image",
            field=models.ImageField(
                null=True, upload_to=pets.models.pet_image_file_path
            ),
        ),
    ]
