# Generated by Django 3.2.22 on 2023-10-30 12:09

from django.db import migrations
import pets.google_image_field
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_is_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=pets.google_image_field.GoogleImageField(null=True, upload_to=pets.models.pet_image_file_path),
        ),
    ]
