# Generated by Django 3.2.22 on 2023-11-26 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='adopted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
