# Generated by Django 3.2.22 on 2023-10-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_profile_picture'),
        ('user', '0004_auto_20231029_0912'),
    ]

    operations = [
    ]
